require 'fastlane/action'
require_relative '../helper/browserstack_helper'
require 'json'

module Fastlane
  module Actions
    module SharedValues
      BROWSERSTACK_APP_ID ||= :BROWSERSTACK_APP_ID
    end
    class UploadToBrowserstackAppAutomateAction < Action
      SUPPORTED_FILE_EXTENSIONS = ["apk", "ipa", "aab"]
      UPLOAD_API_ENDPOINT = "https://api-cloud.browserstack.com/app-automate/upload"

      def self.run(params)
        browserstack_username = params[:browserstack_username] # Required
        browserstack_access_key = params[:browserstack_access_key] # Required
        custom_id = params[:custom_id]
        file_path = params[:file_path].to_s # Required
        ios_keychain_support = params[:ios_keychain_support]

        validate_file_path(file_path)
        validate_ios_keychain_support(ios_keychain_support) unless ios_keychain_support.nil?

        UI.message("Uploading app to BrowserStack AppAutomate...")

        browserstack_app_id = Helper::BrowserstackHelper.upload_file(browserstack_username, browserstack_access_key, file_path, UPLOAD_API_ENDPOINT, custom_id, ios_keychain_support)

        # Set 'BROWSERSTACK_APP_ID' environment variable, if app upload was successful.
        ENV['BROWSERSTACK_APP_ID'] = browserstack_app_id

        UI.success("Successfully uploaded app " + file_path + " to BrowserStack AppAutomate with app_url : " + browserstack_app_id)

        UI.success("Setting Environment variable BROWSERSTACK_APP_ID = " + browserstack_app_id)

        # Setting app id in SharedValues, which can be used by other fastlane actions.
        Actions.lane_context[SharedValues::BROWSERSTACK_APP_ID] = browserstack_app_id
      end

      # Validate file_path.
      def self.validate_file_path(file_path)
        UI.user_error!("No file found at '#{file_path}'.") unless File.exist?(file_path)

        # Validate file extension.
        file_path_parts = file_path.split(".")
        unless file_path_parts.length > 1 && SUPPORTED_FILE_EXTENSIONS.include?(file_path_parts.last)
          UI.user_error!("file_path is invalid, only files with extensions " + SUPPORTED_FILE_EXTENSIONS.to_s + " are allowed to be uploaded.")
        end
      end

      # Validate ios_keychain_support
      def self.validate_ios_keychain_support(ios_keychain_support)
        platform = Actions.lane_context[Actions::SharedValues::PLATFORM_NAME]
        if !platform.nil? && platform != :ios
          # Check if platform is specified and not ios
          # If so, then raise error.
          UI.user_error!("ios_keychain_support param can only be used with platform ios")
        end
        unless ['true', 'false'].include?(ios_keychain_support.to_s)
          UI.user_error!("ios_keychain_support should be either 'true' or 'false'.")
        end
      end

      def self.description
        "Uploads IPA and APK files to BrowserStack AppAutomate for running automated tests."
      end

      def self.authors
        ["Hitesh Raghuvanshi"]
      end

      def self.details
        "Uploads IPA and APK files to BrowserStack AppAutomate for running automated tests."
      end

      def self.output
        [
          ['BROWSERSTACK_APP_ID', 'App id of uploaded app.']
        ]
      end

      def self.default_file_path
        platform = Actions.lane_context[Actions::SharedValues::PLATFORM_NAME]
        if platform == :ios
          # Shared value for ipa path if it was generated by gym https://docs.fastlane.tools/actions/gym/.
          return Actions.lane_context[Actions::SharedValues::IPA_OUTPUT_PATH]
        else
          # Shared value for apk/aab if it was generated by gradle.
          apk_path = Actions.lane_context[Actions::SharedValues::GRADLE_APK_OUTPUT_PATH]
          aab_path = Actions.lane_context[Actions::SharedValues::GRADLE_AAB_OUTPUT_PATH]

          if !apk_path.nil?
            return apk_path
          else
            return aab_path
          end
        end
      end

      def self.available_options
        [
          FastlaneCore::ConfigItem.new(key: :browserstack_username,
                                       description: "BrowserStack's username",
                                       optional: false,
                                       is_string: true,
                                       verify_block: proc do |value|
                                         UI.user_error!("No browserstack_username given.") if value.to_s.empty?
                                       end),
          FastlaneCore::ConfigItem.new(key: :browserstack_access_key,
                                       description: "BrowserStack's access key",
                                       optional: false,
                                       is_string: true,
                                       verify_block: proc do |value|
                                         UI.user_error!("No browserstack_access_key given.") if value.to_s.empty?
                                       end),
          FastlaneCore::ConfigItem.new(key: :custom_id,
                                       description: "Custom id",
                                       optional: true,
                                       is_string: true),
          FastlaneCore::ConfigItem.new(key: :file_path,
                                       description: "Path to the app file",
                                       optional: true,
                                       is_string: true,
                                       default_value: default_file_path),
          FastlaneCore::ConfigItem.new(key: :ios_keychain_support,
                                       description: "ios_keychain_support",
                                       optional: true,
                                       is_string: true)
        ]
      end

      def self.is_supported?(platform)
        [:ios, :android].include?(platform)
      end

      def self.example_code
        [
          'upload_to_browserstack_app_automate',
          'upload_to_browserstack_app_automate(
            browserstack_username: ENV["BROWSERSTACK_USERNAME"],
            browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
            file_path: "path_to_apk_or_ipa_file"
           )'
        ]
      end
    end
  end
end
